name = "ota-poc"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespace — stores version metadata
[[kv_namespaces]]
binding = "OTA_METADATA"
id = "a47ae8b3ea724817bacf637868e5c8a0"

# R2 Bucket — stores JS bundle files
[[r2_buckets]]
binding = "OTA_BUNDLES"
bucket_name = "ota-bundles"
